<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GitHubAccountManager.Core\GitHubAccountManager.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>GitHubAccountManager</AssemblyName>
    <RootNamespace>GitHubAccountManager.App</RootNamespace>
    <Version>0.1.2</Version>
    <Authors>Ahmed Essam</Authors>
    <Description>Safe Git and GitHub account manager for Windows.</Description>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <PublishDir>$(MSBuildProjectDirectory)\..\..\dist\</PublishDir>
  </PropertyGroup>

</Project>
